sudo: required
services:
  - docker
before_install:
  - docker build -t icecast2 .
  - docker run --name icecast2srv -d -p 8000:8000 icecast2
script:
  - docker ps -a
  - docker exec -it icecast2srv cat /etc/icecast2/icecast.xml